-----------------------------------------------------------------------------------------------
--  Company:    		"Haller + Erne GmbH"
--  Project: 			Sys3xxGateway service
--  File description:   Project components configuration
--  WARNING !!!         Do not edit this file.
--  The content of this file is generated automatically at installation time
-----------------------------------------------------------------------------------------------

require('sys3xx')
require('_qwx_')
require('config')
