-------------------------------------------------------------------------------------------------  Company:    		"Haller + Erne GmbH"--  Project: 			Sys3xxGateway service--  File description:   Standard configuration--  !!! Do not edit this file.--  The content of this file is generated automatically-----------------------------------------------------------------------------------------------custom_cfg_table = {}custom_cfg_line  = {}custom_configuration = true
custom_cfg_line['undefined'] = {  }
--[[	>> begin of section 'QWX output driver settings'  ]]
   heQWXDLL_settings.base_directory= [[C:\Sys3xx]]   heQWXDLL_settings.fifo_max_size = 10000
qwx_idcode_mask = '1111111111111111111111111111111111111111111111111111111111111111'

database['default'] = create_database([[REXROTH-OGS]], [[QTrans]] , [[sys3xx]] ,[[sys3xx]])
-------------------------------------------------------------------------
function qwx_id_parser(station_name, IDCode)

   local sernum 	= ''
   local model   	= ''

   if valid_str(IDCode) then

		sernum = string.format('%s%s',sernum, string.sub(IDCode,1,64))

   end
   return sernum,model,model
end
-------------------------------------------------------------------------

function qwx_bolt_definition(station_name, IDCode)

   local bolt_pos = ''
   local op_count = ''

   if valid_str(IDCode) then


   end
   if not valid_str(op_count) then op_count = '-1' end

   return bolt_pos,op_count
end

--[[	<< end of section 'QWX output driver settings'  ]]